from jethive.model import Model, unique
from jethive.models.city import City


class Airport(Model):
    c_name = str
    c_code = str
    c_city = City
    
    @classmethod
    def seed(cls):
        return [
            {"name": "Aarhus Airport", "code": "AAR", "city_id": City.pick.with_name("Aarhus").id},
            {"name": "Abidjan-Felix Houphouet Boigny International Airport", "code": "ABJ", "city_id": City.pick.with_name("Abidjan").id},
            {"name": "Abu Dhabi International Airport", "code": "AUH", "city_id": City.pick.with_name("Abu Dhabi").id},
            {"name": "Kotoka International Airport", "code": "ACC", "city_id": City.pick.with_name("Accra").id},
            {"name": "Addis Ababa Bole International Airport", "code": "ADD", "city_id": City.pick.with_name("Addis Ababa").id},
            {"name": "Adelaide Airport", "code": "ADL", "city_id": City.pick.with_name("Adelaide").id},
            {"name": "Aden International Airport", "code": "ADE", "city_id": City.pick.with_name("Aden").id},
            {"name": "Aleppo International Airport", "code": "ALP", "city_id": City.pick.with_name("Aleppo").id},
            {"name": "Borg El Arab Airport", "code": "HBE", "city_id": City.pick.with_name("Alexandria").id},
            {"name": "Houari Boumediene Airport", "code": "ALG", "city_id": City.pick.with_name("Algiers").id},
            {"name": "Almaty International Airport", "code": "ALA", "city_id": City.pick.with_name("Almaty").id},
            {"name": "Queen Alia International Airport", "code": "AMM", "city_id": City.pick.with_name("Amman").id},
            {"name": "Amsterdam Airport Schiphol", "code": "AMS", "city_id": City.pick.with_name("Amsterdam").id},
            {"name": "Andorra la Vella Heliport", "code": "ALV", "city_id": City.pick.with_name("Andorra la Vella").id},
            {"name": "Ankara Esenboğa Airport", "code": "ESB", "city_id": City.pick.with_name("Ankara").id},
            {"name": "Rabah Bitat Airport", "code": "AAE", "city_id": City.pick.with_name("Annaba").id},
            {"name": "Seychelles International Airport", "code": "SEZ", "city_id": City.pick.with_name("Anse Royale").id},
            {"name": "Ivato International Airport", "code": "TNR", "city_id": City.pick.with_name("Antananarivo").id},
            {"name": "Antwerp International Airport", "code": "ANR", "city_id": City.pick.with_name("Antwerp").id},
            {"name": "Faleolo International Airport", "code": "APW", "city_id": City.pick.with_name("Apia").id},
            {"name": "Rodríguez Ballón International Airport", "code": "AQP", "city_id": City.pick.with_name("Arequipa").id},
            {"name": "Argyle International Airport", "code": "SVD", "city_id": City.pick.with_name("Arnos Vale").id},
            {"name": "Ashgabat International Airport", "code": "ASB", "city_id": City.pick.with_name("Ashgabat").id},
            {"name": "Asmara International Airport", "code": "ASM", "city_id": City.pick.with_name("Asmara").id},
            {"name": "Silvio Pettirossi International Airport", "code": "ASU", "city_id": City.pick.with_name("Asunción").id},
            {"name": "Athens International Airport", "code": "ATH", "city_id": City.pick.with_name("Athens").id},
            {"name": "Auckland Airport", "code": "AKL", "city_id": City.pick.with_name("Auckland").id},
            {"name": "Osvaldo Vieira International Airport", "code": "OBB", "city_id": City.pick.with_name("Bafatá").id},
            {"name": "Baghdad International Airport", "code": "BGW", "city_id": City.pick.with_name("Baghdad").id},
            {"name": "Bonriki International Airport", "code": "TRW", "city_id": City.pick.with_name("Bairiki").id},
            {"name": "Heydar Aliyev International Airport", "code": "GYD", "city_id": City.pick.with_name("Baku").id},
            {"name": "Modibo Keïta International Airport", "code": "BKO", "city_id": City.pick.with_name("Bamako").id},
            {"name": "Banfora Airport", "code": "BNR", "city_id": City.pick.with_name("Banfora").id},
            {"name": "Suvarnabhumi Airport", "code": "BKK", "city_id": City.pick.with_name("Bangkok").id},
            {"name": "Banja Luka International Airport", "code": "BNX", "city_id": City.pick.with_name("Banja Luka").id},
            {"name": "Banjul International Airport", "code": "BJL", "city_id": City.pick.with_name("Banjul").id},
            {"name": "Barcelona-El Prat Airport", "code": "BCN", "city_id": City.pick.with_name("Barcelona").id},
            {"name": "Barisal Airport", "code": "BZL", "city_id": City.pick.with_name("Barisal").id},
            {"name": "Basra International Airport", "code": "BSR", "city_id": City.pick.with_name("Basra").id},
            {"name": "Robert L. Bradshaw International Airport", "code": "SKB", "city_id": City.pick.with_name("Basseterre").id},
            {"name": "Bata Airport", "code": "BSG", "city_id": City.pick.with_name("Bata").id},
            {"name": "Batna International Airport", "code": "BLJ", "city_id": City.pick.with_name("Batna").id},
            {"name": "Presidente Nicolau Lobato International Airport", "code": "DILL", "city_id": City.pick.with_name("Baucau").id},
            {"name": "Sir Seewoosagur Ramgoolam International Airport", "code": "MRU", "city_id": City.pick.with_name("Beau Bassin-Rose Hill").id},
            {"name": "Beijing Capital International Airport", "code": "PEK", "city_id": City.pick.with_name("Beijing").id},
            {"name": "Beirut-Rafic Hariri International Airport", "code": "BEY", "city_id": City.pick.with_name("Beirut").id},
            {"name": "Belgrade Nikola Tesla Airport", "code": "BEG", "city_id": City.pick.with_name("Belgrade").id},
            {"name": "Philip S. W. Goldson International Airport", "code": "BZE", "city_id": City.pick.with_name("Belize City").id},
            {"name": "Hector Silva Airstrip", "code": "BCV", "city_id": City.pick.with_name("Belmopan").id},
            {"name": "Belo Horizonte International Airport", "code": "CNF", "city_id": City.pick.with_name("Belo Horizonte").id},
            {"name": "Benina International Airport", "code": "BEN", "city_id": City.pick.with_name("Benghazi").id},
            {"name": "Catumbela Airport", "code": "CBT", "city_id": City.pick.with_name("Benguela").id},
            {"name": "Bergen Airport, Flesland", "code": "BGO", "city_id": City.pick.with_name("Bergen").id},
            {"name": "Berlin Brandenburg Airport", "code": "BER", "city_id": City.pick.with_name("Berlin").id},
            {"name": "Bern Airport", "code": "BRN", "city_id": City.pick.with_name("Bern").id},
            {"name": "Bijeljina International Airport", "code": "BXX", "city_id": City.pick.with_name("Bijeljina").id},
            {"name": "Bangui M'Poko International Airport", "code": "BFF", "city_id": City.pick.with_name("Bimbo").id},
            {"name": "Malta International Airport", "code": "MLA", "city_id": City.pick.with_name("Birkirkara").id},
            {"name": "Manas International Airport", "code": "FRU", "city_id": City.pick.with_name("Bishkek").id},
            {"name": "St. Paul the Apostle Airport", "code": "KZO", "city_id": City.pick.with_name("Bitola").id},
            {"name": "Chileka International Airport", "code": "BLZ", "city_id": City.pick.with_name("Blantyre").id},
            {"name": "Bo Airport", "code": "KBS", "city_id": City.pick.with_name("Bo").id},
            {"name": "Bobo-Dioulasso Airport", "code": "BOY", "city_id": City.pick.with_name("Bobo-Dioulasso").id},
            {"name": "El Dorado International Airport", "code": "BOG", "city_id": City.pick.with_name("Bogotá").id},
            {"name": "Bohicon Airport", "code": "OACI", "city_id": City.pick.with_name("Bohicon").id},
            {"name": "V.C. Bird International Airport", "code": "ANUU", "city_id": City.pick.with_name("Bolans").id},
            {"name": "Brasília International Airport", "code": "BSB", "city_id": City.pick.with_name("Brasília").id},
            {"name": "M. R. Štefánik Airport", "code": "BTS", "city_id": City.pick.with_name("Bratislava").id},
            {"name": "Maya-Maya Airport", "code": "BZV", "city_id": City.pick.with_name("Brazzaville").id},
            {"name": "Brest Bretagne Airport", "code": "BES", "city_id": City.pick.with_name("Brest").id},
            {"name": "Grantley Adams International Airport", "code": "BGI", "city_id": City.pick.with_name("Bridgetown").id},
            {"name": "Brisbane Airport", "code": "BNE", "city_id": City.pick.with_name("Brisbane").id},
            {"name": "Brno-Tuřany Airport", "code": "BRQ", "city_id": City.pick.with_name("Brno").id},
            {"name": "Bruges Airport", "code": "OST", "city_id": City.pick.with_name("Bruges").id},
            {"name": "Brussels Airport", "code": "BRU", "city_id": City.pick.with_name("Brussels").id},
            {"name": "Henri Coandă International Airport", "code": "OTP", "city_id": City.pick.with_name("Bucharest").id},
            {"name": "Budapest Ferenc Liszt International Airport", "code": "BUD", "city_id": City.pick.with_name("Budapest").id},
            {"name": "Ministro Pistarini International Airport", "code": "EZE", "city_id": City.pick.with_name("Buenos Aires").id},
            {"name": "Bujumbura International Airport", "code": "BJM", "city_id": City.pick.with_name("Bujumbura").id},
            {"name": "Joshua Mqabuko Nkomo International Airport", "code": "BUQ", "city_id": City.pick.with_name("Bulawayo").id},
            {"name": "Burgas Airport", "code": "BOJ", "city_id": City.pick.with_name("Burgas").id},
            {"name": "Makamba Airport", "code": "KAR", "city_id": City.pick.with_name("Bururi").id},
            {"name": "Gimhae International Airport", "code": "PUS", "city_id": City.pick.with_name("Busan").id},
            {"name": "Butare Airport", "code": "BTQ", "city_id": City.pick.with_name("Butare").id},
            {"name": "Mihail Kogălniceanu International Airport", "code": "CND", "city_id": City.pick.with_name("Bălți").id},
            {"name": "Cairo International Airport", "code": "CAI", "city_id": City.pick.with_name("Cairo").id},
            {"name": "Cap-Haïtien International Airport", "code": "CAP", "city_id": City.pick.with_name("Cap-Haïtien").id},
            {"name": "Simón Bolívar International Airport", "code": "CCS", "city_id": City.pick.with_name("Caracas").id},
            {"name": "Chaguanas Heliport", "code": "POS", "city_id": City.pick.with_name("Chaguanas").id},
            {"name": "Brussels South Charleroi Airport", "code": "CRL", "city_id": City.pick.with_name("Charleroi").id},
            {"name": "Vance W. Amory International Airport", "code": "NEV", "city_id": City.pick.with_name("Charlestown").id},
            {"name": "Chișinău International Airport", "code": "KIV", "city_id": City.pick.with_name("Chișinău").id},
            {"name": "Guarani International Airport", "code": "AGT", "city_id": City.pick.with_name("Ciudad del Este").id},
            {"name": "Avram Iancu Cluj International Airport", "code": "CLJ", "city_id": City.pick.with_name("Cluj-Napoca").id},
            {"name": "Jorge Wilstermann International Airport", "code": "CBB", "city_id": City.pick.with_name("Cochabamba").id},
            {"name": "Bandaranaike International Airport", "code": "CMB", "city_id": City.pick.with_name("Colombo").id},
            {"name": "Shah Amanat International Airport", "code": "CGP", "city_id": City.pick.with_name("Comilla").id},
            {"name": "Conakry International Airport", "code": "CKY", "city_id": City.pick.with_name("Conakry").id},
            {"name": "Mohamed Boudiaf International Airport", "code": "CZL", "city_id": City.pick.with_name("Constantine").id},
            {"name": "Copenhagen Airport", "code": "CPH", "city_id": City.pick.with_name("Copenhagen").id},
            {"name": "Cork Airport", "code": "ORK", "city_id": City.pick.with_name("Cork").id},
            {"name": "Corozal Airport", "code": "CZH", "city_id": City.pick.with_name("Corozal").id},
            {"name": "Cadjehoun Airport", "code": "COO", "city_id": City.pick.with_name("Cotonou").id},
            {"name": "Ingeniero Aeronáutico Ambrosio L.V. Taravella International Airport", "code": "COR", "city_id": City.pick.with_name("Córdoba").id},
            {"name": "Blaise Diagne International Airport", "code": "DSS", "city_id": City.pick.with_name("Dakar").id},
            {"name": "Damascus International Airport", "code": "DAM", "city_id": City.pick.with_name("Damascus").id},
            {"name": "Dangriga Airport", "code": "DGA", "city_id": City.pick.with_name("Dangriga").id},
            {"name": "Julius Nyerere International Airport", "code": "DAR", "city_id": City.pick.with_name("Dar es Salaam").id},
            {"name": "Daugavpils International Airport", "code": "DGP", "city_id": City.pick.with_name("Daugavpils").id},
            {"name": "Debrecen International Airport", "code": "DEB", "city_id": City.pick.with_name("Debrecen").id},
            {"name": "Hazrat Shahjalal International Airport", "code": "DAC", "city_id": City.pick.with_name("Dhaka").id},
            {"name": "Nicolau Lobato International Airport", "code": "DIL", "city_id": City.pick.with_name("Dili").id},
            {"name": "Aba Tenna Dejazmach Yohannes International Airport", "code": "DIR", "city_id": City.pick.with_name("Dire Dawa").id},
            {"name": "Ambouli International Airport", "code": "JIB", "city_id": City.pick.with_name("Djibouti City").id},
            {"name": "Djougou Airport", "code": "DJA", "city_id": City.pick.with_name("Djougou").id},
            {"name": "Dodoma Airport", "code": "DOD", "city_id": City.pick.with_name("Dodoma").id},
            {"name": "Hamad International Airport", "code": "DOH", "city_id": City.pick.with_name("Doha").id},
            {"name": "Douala International Airport", "code": "DLA", "city_id": City.pick.with_name("Douala").id},
            {"name": "Dubai International Airport", "code": "DXB", "city_id": City.pick.with_name("Dubai").id},
            {"name": "Dublin Airport", "code": "DUB", "city_id": City.pick.with_name("Dublin").id},
            {"name": "Mother Teresa International Airport", "code": "TIA", "city_id": City.pick.with_name("Durrës").id},
            {"name": "Dushanbe International Airport", "code": "DYU", "city_id": City.pick.with_name("Dushanbe").id},
            {"name": "Dédougou Airport", "code": "DGU", "city_id": City.pick.with_name("Dédougou").id},
            {"name": "Atarot Airport", "code": "JRS", "city_id": City.pick.with_name("East Jerusalem").id},
            {"name": "Edinburgh Airport", "code": "EDI", "city_id": City.pick.with_name("Edinburgh").id},
            {"name": "Erdenet Airport", "code": "ERT", "city_id": City.pick.with_name("Erdenet").id},
            {"name": "Toulouse–Blagnac Airport", "code": "TLS", "city_id": City.pick.with_name("Escaldes-Engordany").id},
            {"name": "Luxembourg Airport", "code": "LUX", "city_id": City.pick.with_name("Esch-sur-Alzette").id},
            {"name": "Fieri Airport", "code": "FIE", "city_id": City.pick.with_name("Fier").id},
            {"name": "Léopold Sédar Senghor International Airport", "code": "DKR", "city_id": City.pick.with_name("Dakar").id},
            {"name": "Los Angeles International Airport", "code": "LAX", "city_id": City.pick.with_name("Los Angeles").id},
            {"name": "Ljubljana Jože Pučnik Airport", "code": "LJU", "city_id": City.pick.with_name("Ljubljana").id},
            {"name": "Lusaka Kenneth Kaunda International Airport", "code": "LUN", "city_id": City.pick.with_name("Lusaka").id},
            {"name": "Adolfo Suárez Madrid–Barajas Airport", "code": "MAD", "city_id": City.pick.with_name("Madrid").id},
            {"name": "Marshall Islands International Airport", "code": "MAJ", "city_id": City.pick.with_name("Majuro").id},
            {"name": "Malabo International Airport", "code": "SSG", "city_id": City.pick.with_name("Malabo").id},
            {"name": "Malakal Airport", "code": "MAK", "city_id": City.pick.with_name("Malakal").id},
            {"name": "Malanje Airport", "code": "MEG", "city_id": City.pick.with_name("Malanje").id},
            {"name": "Velana International Airport", "code": "MLE", "city_id": City.pick.with_name("Malé").id},
            {"name": "Augusto C. Sandino International Airport", "code": "MGA", "city_id": City.pick.with_name("Managua").id},
            {"name": "Manchester Airport", "code": "MAN", "city_id": City.pick.with_name("Manchester").id},
            {"name": "Ninoy Aquino International Airport", "code": "MNL", "city_id": City.pick.with_name("Manila").id},
            {"name": "La Chinita International Airport", "code": "MAR", "city_id": City.pick.with_name("Maracaibo").id},
            {"name": "Maribor Edvard Rusjan Airport", "code": "MBX", "city_id": City.pick.with_name("Maribor").id},
            {"name": "Marseille Provence Airport", "code": "MRS", "city_id": City.pick.with_name("Marseille").id},
            {"name": "Moshoeshoe I International Airport", "code": "MSU", "city_id": City.pick.with_name("Maseru").id},
            {"name": "Mashhad International Airport", "code": "MHD", "city_id": City.pick.with_name("Mashhad").id},
            {"name": "Maputo International Airport", "code": "MPM", "city_id": City.pick.with_name("Matola").id},
            {"name": "Maun Airport", "code": "MUB", "city_id": City.pick.with_name("Maun").id},
            {"name": "Mazar-i-Sharif International Airport", "code": "MZR", "city_id": City.pick.with_name("Mazar-i-Sharif").id},
            {"name": "King Mswati III International Airport", "code": "SHO", "city_id": City.pick.with_name("Mbabane").id},
            {"name": "Olaya Herrera Airport", "code": "EOH", "city_id": City.pick.with_name("Medellín").id},
            {"name": "Melbourne Airport", "code": "MEL", "city_id": City.pick.with_name("Melbourne").id},
            {"name": "Governor Francisco Gabrielli International Airport", "code": "MDZ", "city_id": City.pick.with_name("Mendoza").id},
            {"name": "Mexico City International Airport", "code": "MEX", "city_id": City.pick.with_name("Mexico City").id},
            {"name": "Milan Malpensa Airport", "code": "MXP", "city_id": City.pick.with_name("Milan").id},
            {"name": "Amílcar Cabral International Airport", "code": "SID", "city_id": City.pick.with_name("Mindelo").id},
            {"name": "Gabala International Airport", "code": "GBB", "city_id": City.pick.with_name("Mingachevir").id},
            {"name": "Minsk National Airport", "code": "MSQ", "city_id": City.pick.with_name("Minsk").id},
            {"name": "La Aurora International Airport", "code": "GUA", "city_id": City.pick.with_name("Mixco").id},
            {"name": "Aden Adde International Airport", "code": "MGQ", "city_id": City.pick.with_name("Mogadishu").id},
            {"name": "Mogilev Airport", "code": "MVQ", "city_id": City.pick.with_name("Mogilev").id},
            {"name": "Sir Seretse Khama International Airport", "code": "GBE", "city_id": City.pick.with_name("Molepolole").id},
            {"name": "Moi International Airport", "code": "MBA", "city_id": City.pick.with_name("Mombasa").id},
            {"name": "Héliport de Monaco", "code": "MCM", "city_id": City.pick.with_name("Monaco").id},
            {"name": "Roberts International Airport", "code": "ROB", "city_id": City.pick.with_name("Monrovia").id},
            {"name": "Circom International Heliport", "code": "QCM", "city_id": City.pick.with_name("Monte Carlo").id},
            {"name": "Sangster International Airport", "code": "MBJ", "city_id": City.pick.with_name("Montego Bay").id},
            {"name": "Carrasco International Airport", "code": "MVD", "city_id": City.pick.with_name("Montevideo").id},
            {"name": "Prince Said Ibrahim International Airport", "code": "HAH", "city_id": City.pick.with_name("Moroni").id},
            {"name": "Sheremetyevo International Airport", "code": "SVO", "city_id": City.pick.with_name("Moscow").id},
            {"name": "Moundou Airport", "code": "MQQ", "city_id": City.pick.with_name("Moundou").id},
            {"name": "Bahrain International Airport", "code": "BAH", "city_id": City.pick.with_name("Muharraq").id},
            {"name": "Chhatrapati Shivaji Maharaj International Airport", "code": "BOM", "city_id": City.pick.with_name("Mumbai").id},
            {"name": "Muscat International Airport", "code": "MCT", "city_id": City.pick.with_name("Muscat").id},
            {"name": "Mohammed V International Airport", "code": "CMN", "city_id": City.pick.with_name("N'Djamena").id},
            {"name": "Nadi International Airport", "code": "NAN", "city_id": City.pick.with_name("Nadi").id},
            {"name": "Jomo Kenyatta International Airport", "code": "NBO", "city_id": City.pick.with_name("Nairobi").id},
            {"name": "Nakhchivan Airport", "code": "NAJ", "city_id": City.pick.with_name("Nakhchivan").id},
            {"name": "Nakhon Ratchasima Airport", "code": "NAK", "city_id": City.pick.with_name("Nakhon Ratchasima").id},
            {"name": "Namangan Airport", "code": "NMA", "city_id": City.pick.with_name("Namangan").id},
            {"name": "Lynden Pindling International Airport", "code": "NAS", "city_id": City.pick.with_name("Nassau").id},
            {"name": "Nauru International Airport", "code": "INU", "city_id": City.pick.with_name("Nauru").id},
            {"name": "Naypyidaw International Airport", "code": "NYT", "city_id": City.pick.with_name("Naypyidaw").id},
            {"name": "Simon Mwansa Kapwepwe International Airport", "code": "NLA", "city_id": City.pick.with_name("Ndola").id},
            {"name": "Indira Gandhi International Airport", "code": "DEL", "city_id": City.pick.with_name("New Delhi").id},
            {"name": "John F. Kennedy International Airport", "code": "JFK", "city_id": City.pick.with_name("New York City").id},
            {"name": "Roman Tmetuchl International Airport", "code": "ROR", "city_id": City.pick.with_name("Ngerulmud").id},
            {"name": "Niamtougou International Airport", "code": "LRL", "city_id": City.pick.with_name("Ngozi").id},
            {"name": "Diori Hamani International Airport", "code": "NIM", "city_id": City.pick.with_name("Niamey").id},
            {"name": "Larnaca International Airport", "code": "LCA", "city_id": City.pick.with_name("Nicosia").id},
            {"name": "Bemolanga Airport", "code": "NZG", "city_id": City.pick.with_name("Nikki").id},
            {"name": "Podgorica Airport", "code": "TGD", "city_id": City.pick.with_name("Nikšić").id},
            {"name": "Nouadhibou International Airport", "code": "NDB", "city_id": City.pick.with_name("Nouadhibou").id},
            {"name": "Nouakchott–Oumtounsy International Airport", "code": "NKC", "city_id": City.pick.with_name("Nouakchott").id},
            {"name": "Fua'amotu International Airport", "code": "TBU", "city_id": City.pick.with_name("Nukuʻalofa").id},
            {"name": "Nursultan Nazarbayev International Airport", "code": "NQZ", "city_id": City.pick.with_name("Nur-Sultan").id},
            {"name": "Nzérékoré Airport", "code": "NZE", "city_id": City.pick.with_name("Nzérékoré").id},
            {"name": "Khartoum International Airport", "code": "KRT", "city_id": City.pick.with_name("Omdurman").id},
            {"name": "Ahmed Ben Bella Airport", "code": "TLM", "city_id": City.pick.with_name("Oran").id},
            {"name": "Orange Walk Airport", "code": "ORZ", "city_id": City.pick.with_name("Orange Walk").id},
            {"name": "Juan Mendoza Airport", "code": "ORN", "city_id": City.pick.with_name("Oran").id},
            {"name": "Osh International Airport", "code": "OSS", "city_id": City.pick.with_name("Osh").id},
            {"name": "Oslo Gardermoen Airport", "code": "OSL", "city_id": City.pick.with_name("Oslo").id},
            {"name": "Ottawa Macdonald–Cartier International Airport", "code": "YOW", "city_id": City.pick.with_name("Ottawa").id},
            {"name": "Ouagadougou Airport", "code": "OUA", "city_id": City.pick.with_name("Ouagadougou").id},
            {"name": "Ouahigouya Airport", "code": "OUG", "city_id": City.pick.with_name("Ouahigouya").id},
            {"name": "Wattay International Airport", "code": "VTE", "city_id": City.pick.with_name("Vientiane").id},
            {"name": "Vilnius Airport", "code": "VNO", "city_id": City.pick.with_name("Vilnius").id},
            {"name": "Gdańsk Lech Wałęsa Airport", "code": "GDN", "city_id": City.pick.with_name("Vitebsk").id},
            {"name": "Vlorë International Airport", "code": "VLO", "city_id": City.pick.with_name("Vlorë").id},
            {"name": "Warsaw Chopin Airport", "code": "WAW", "city_id": City.pick.with_name("Warsaw").id},
            {"name": "Washington Dulles International Airport", "code": "IAD", "city_id": City.pick.with_name("Washington, D.C.").id},
            {"name": "Wellington International Airport", "code": "WLG", "city_id": City.pick.with_name("Wellington").id},
            {"name": "Chuuk International Airport", "code": "TKK", "city_id": City.pick.with_name("Weno").id},
            {"name": "Hosea Kutako International Airport", "code": "WDH", "city_id": City.pick.with_name("Windhoek").id},
            {"name": "George F. L. Charles Airport", "code": "SLU", "city_id": City.pick.with_name("Woodlands").id},
            {"name": "Yamoussoukro Airport", "code": "ASK", "city_id": City.pick.with_name("Yamoussoukro").id},
            {"name": "Yangon International Airport", "code": "RGN", "city_id": City.pick.with_name("Yangon").id},
            {"name": "Yaoundé Nsimalen International Airport", "code": "NSI", "city_id": City.pick.with_name("Yaoundé").id},
            {"name": "Yaren International Airport", "code": "INY", "city_id": City.pick.with_name("Yaren").id},
            {"name": "Zvartnots International Airport", "code": "EVN", "city_id": City.pick.with_name("Yerevan").id},
            {"name": "Yokohama International Airport", "code": "YOK", "city_id": City.pick.with_name("Yokohama").id},
            {"name": "Zagreb Franjo Tuđman Airport", "code": "ZAG", "city_id": City.pick.with_name("Zagreb").id},
            {"name": "Prince Hasan Air Base", "code": "ADJ", "city_id": City.pick.with_name("Zarqa").id},
            {"name": "Zenica Airport", "code": "ZJI", "city_id": City.pick.with_name("Zenica").id},
            {"name": "Zinder Airport", "code": "ZND", "city_id": City.pick.with_name("Zinder").id},
            {"name": "Zurich Airport", "code": "ZRH", "city_id": City.pick.with_name("Zurich").id},
            {"name": "Saint Petersburg Pulkovo Airport", "code": "LED", "city_id": City.pick.with_name("Saint Petersburg").id},
            {"name": "Novosibirsk Tolmachevo Airport", "code": "OVB", "city_id": City.pick.with_name("Novosibirsk").id},
            {"name": "Yekaterinburg Koltsovo Airport", "code": "SVX", "city_id": City.pick.with_name("Yekaterinburg").id},
            {"name": "Nizhny Novgorod International Airport", "code": "GOJ", "city_id": City.pick.with_name("Nizhny Novgorod").id},
            {"name": "Kazan International Airport", "code": "KZN", "city_id": City.pick.with_name("Kazan").id},
            {"name": "Chelyabinsk Balandino Airport", "code": "CEK", "city_id": City.pick.with_name("Chelyabinsk").id},
            {"name": "Omsk Tsentralny Airport", "code": "OMS", "city_id": City.pick.with_name("Omsk").id},
            {"name": "Samara Kurumoch International Airport", "code": "KUF", "city_id": City.pick.with_name("Samara").id},
            {"name": "Rostov-on-Don Platov International Airport", "code": "ROV", "city_id": City.pick.with_name("Rostov-on-Don").id},
            {"name": "Ufa International Airport", "code": "UFA", "city_id": City.pick.with_name("Ufa").id},
            {"name": "Krasnoyarsk Yemelyanovo Airport", "code": "KJA", "city_id": City.pick.with_name("Krasnoyarsk").id},
            {"name": "Perm Bolshoye Savino Airport", "code": "PEE", "city_id": City.pick.with_name("Perm").id},
            {"name": "Voronezh International Airport", "code": "VOZ", "city_id": City.pick.with_name("Voronezh").id},
            {"name": "Volgograd International Airport", "code": "VOG", "city_id": City.pick.with_name("Volgograd").id},
            {"name": "Saratov Gagarin International Airport", "code": "GSV", "city_id": City.pick.with_name("Saratov").id},
            {"name": "Krasnodar International Airport", "code": "KRR", "city_id": City.pick.with_name("Krasnodar").id},
            {"name": "Tolyatti Kurumoch International Airport", "code": "KUF", "city_id": City.pick.with_name("Tolyatti").id},
            {"name": "Izhevsk Airport", "code": "IJK", "city_id": City.pick.with_name("Izhevsk").id},
            {"name": "Yaroslavl Tunoshna Airport", "code": "IAR", "city_id": City.pick.with_name("Yaroslavl").id},
            {"name": "Barnaul Airport", "code": "BAX", "city_id": City.pick.with_name("Barnaul").id},
            {"name": "Vladivostok International Airport", "code": "VVO", "city_id": City.pick.with_name("Vladivostok").id},
            {"name": "Irkutsk International Airport", "code": "IKT", "city_id": City.pick.with_name("Irkutsk").id},
            {"name": "Khabarovsk Novy Airport", "code": "KHV", "city_id": City.pick.with_name("Khabarovsk").id},
            {"name": "Kemerovo International Airport", "code": "KEJ", "city_id": City.pick.with_name("Kemerovo").id},
            {"name": "Novokuznetsk Spichenkovo Airport", "code": "NOZ", "city_id": City.pick.with_name("Novokuznetsk").id},
            {"name": "Orenburg Tsentralny Airport", "code": "REN", "city_id": City.pick.with_name("Orenburg").id},
            {"name": "Ryazan Dyagilevo Airport", "code": "RZN", "city_id": City.pick.with_name("Ryazan").id},
            {"name": "Tomsk Bogashevo Airport", "code": "TOF", "city_id": City.pick.with_name("Tomsk").id},
            {"name": "Astrakhan Narimanovo Airport", "code": "ASF", "city_id": City.pick.with_name("Astrakhan").id},
            {"name": "Penza Airport", "code": "PEZ", "city_id": City.pick.with_name("Penza").id},
            {"name": "Lipetsk Airport", "code": "LPK", "city_id": City.pick.with_name("Lipetsk").id},
            {"name": "Tula Yasnaya Polyana Airport", "code": "ULA", "city_id": City.pick.with_name("Tula").id},
            {"name": "Kurgan Airport", "code": "KRO", "city_id": City.pick.with_name("Kurgan").id},
            {"name": "Ivanovo Yuzhny Airport", "code": "IWA", "city_id": City.pick.with_name("Ivanovo").id},
            {"name": "Ulan-Ude Mukhino Airport", "code": "UUD", "city_id": City.pick.with_name("Ulan-Ude").id},
            {"name": "Bryansk International Airport", "code": "BZK", "city_id": City.pick.with_name("Bryansk").id},
            {"name": "Kursk Vostochny Airport", "code": "URS", "city_id": City.pick.with_name("Kursk").id},
            {"name": "Tver Migalovo Airport", "code": "KLD", "city_id": City.pick.with_name("Tver").id},
            {"name": "Magnitogorsk Airport", "code": "MQF", "city_id": City.pick.with_name("Magnitogorsk").id},
            {"name": "Kaliningrad Khrabrovo Airport", "code": "KGD", "city_id": City.pick.with_name("Kaliningrad").id},
            {"name": "Belgorod International Airport", "code": "EGO", "city_id": City.pick.with_name("Belgorod").id},
            {"name": "Nizhnevartovsk Airport", "code": "NJC", "city_id": City.pick.with_name("Nizhnevartovsk").id},
            {"name": "Smolensk Airport", "code": "LNX", "city_id": City.pick.with_name("Smolensk").id},
            {"name": "Kaluga Grabtsevo Airport", "code": "KLF", "city_id": City.pick.with_name("Kaluga").id},
            {"name": "Chita Kadala Airport", "code": "HTA", "city_id": City.pick.with_name("Chita").id},
            {"name": "Kostroma Airport", "code": "KMW", "city_id": City.pick.with_name("Kostroma").id},
            {"name": "Orel Tsentralny Airport", "code": "OEL", "city_id": City.pick.with_name("Orel").id},
            {"name": "Volzhsky Airport", "code": "VLK", "city_id": City.pick.with_name("Volzhsky").id},
            {"name": "Novorossiysk Airport", "code": "NOI", "city_id": City.pick.with_name("Novorossiysk").id},
            {"name": "Taganrog Airport", "code": "TGK", "city_id": City.pick.with_name("Taganrog").id},
            {"name": "Norilsk Alykel Airport", "code": "NSK", "city_id": City.pick.with_name("Norilsk").id},
            {"name": "Zheleznogorsk Airport", "code": "ZIX", "city_id": City.pick.with_name("Zheleznogorsk").id},
            {"name": "Vologda Airport", "code": "VGD", "city_id": City.pick.with_name("Vologda").id},
            {"name": "Sterlitamak Airport", "code": "UKS", "city_id": City.pick.with_name("Sterlitamak").id},
            {"name": "Angarsk Airport", "code": "IGA", "city_id": City.pick.with_name("Angarsk").id},
            {"name": "Blagoveshchensk Ignatyevo Airport", "code": "BQS", "city_id": City.pick.with_name("Blagoveshchensk").id},
            {"name": "Yuzhno-Sakhalinsk Airport", "code": "UUS", "city_id": City.pick.with_name("Yuzhno-Sakhalinsk").id},
            {"name": "Veliky Novgorod Airport", "code": "NOZ", "city_id": City.pick.with_name("Veliky Novgorod").id},
            {"name": "Nalchik Airport", "code": "NAL", "city_id": City.pick.with_name("Nalchik").id},
            {"name": "Cherepovets Airport", "code": "CEE", "city_id": City.pick.with_name("Cherepovets").id},
            {"name": "Huelva Airport", "code": "HEV", "city_id": City.pick.with_name("Huelva").id},
            {"name": "Lipeck Airport", "code": "LPK", "city_id": City.pick.with_name("Lipeck").id},
            {"name": "Abakan International Airport", "code": "ABA", "city_id": City.pick.with_name("Abakan").id},
        ]