from jethive.model import Model
from jethive.models.manufacturer import Manufacturer


class PlaneType(Model):
    c_name = str
    c_manufacturer = Manufacturer

    @classmethod
    def seed(cls):
        return [
            { 'name': 'A320', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A330', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A350', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A380', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A220', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A340', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A310', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A321', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A319', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': 'A330neo', 'manufacturer_id': Manufacturer.pick.with_name('Airbus').id },
            { 'name': '737', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '747', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '777', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '787', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '727', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '757', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '767', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '737 MAX', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '707', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': '787-10', 'manufacturer_id': Manufacturer.pick.with_name('Boeing').id },
            { 'name': 'CRJ', 'manufacturer_id': Manufacturer.pick.with_name('Bombardier').id },
            { 'name': 'Q400', 'manufacturer_id': Manufacturer.pick.with_name('Bombardier').id },
            { 'name': 'Global 7500', 'manufacturer_id': Manufacturer.pick.with_name('Bombardier').id },
            { 'name': 'Challenger 300', 'manufacturer_id': Manufacturer.pick.with_name('Bombardier').id },
            { 'name': 'Learjet 75', 'manufacturer_id': Manufacturer.pick.with_name('Bombardier').id },
            { 'name': 'Embraer E-Jet', 'manufacturer_id': Manufacturer.pick.with_name('Embraer').id },
            { 'name': 'Embraer Legacy 650', 'manufacturer_id': Manufacturer.pick.with_name('Embraer').id },
            { 'name': 'Gulfstream G550', 'manufacturer_id': Manufacturer.pick.with_name('Gulfstream Aerospace').id },
            { 'name': 'Gulfstream G650', 'manufacturer_id': Manufacturer.pick.with_name('Gulfstream Aerospace').id },
            { 'name': 'Cessna Citation', 'manufacturer_id': Manufacturer.pick.with_name('Cessna').id },
            { 'name': 'Cessna Caravan', 'manufacturer_id': Manufacturer.pick.with_name('Cessna').id },
            { 'name': 'Dassault Falcon', 'manufacturer_id': Manufacturer.pick.with_name('Dassault Aviation').id },
            { 'name': 'Saab 340', 'manufacturer_id': Manufacturer.pick.with_name('Saab AB').id },
            { 'name': 'Saab 2000', 'manufacturer_id': Manufacturer.pick.with_name('Saab AB').id },
            { 'name': 'Sukhoi Superjet', 'manufacturer_id': Manufacturer.pick.with_name('Sukhoi').id },
            { 'name': 'Sukhoi Su-35', 'manufacturer_id': Manufacturer.pick.with_name('Sukhoi').id },
            { 'name': 'Piper PA-28', 'manufacturer_id': Manufacturer.pick.with_name('Piper Aircraft').id },
            { 'name': 'Piper M600', 'manufacturer_id': Manufacturer.pick.with_name('Piper Aircraft').id },
            { 'name': 'Diamond DA40', 'manufacturer_id': Manufacturer.pick.with_name('Diamond Aircraft').id },
            { 'name': 'Diamond DA42', 'manufacturer_id': Manufacturer.pick.with_name('Diamond Aircraft').id },
            { 'name': 'Beechcraft King Air', 'manufacturer_id': Manufacturer.pick.with_name('Beechcraft').id },
            { 'name': 'Beechcraft Bonanza', 'manufacturer_id': Manufacturer.pick.with_name('Beechcraft').id },
            { 'name': 'Antonov An-124', 'manufacturer_id': Manufacturer.pick.with_name('Antonov').id },
            { 'name': 'Antonov An-225', 'manufacturer_id': Manufacturer.pick.with_name('Antonov').id },
            { 'name': 'Kawasaki P-1', 'manufacturer_id': Manufacturer.pick.with_name('Kawasaki Heavy Industries').id },
            { 'name': 'Kawasaki C-2', 'manufacturer_id': Manufacturer.pick.with_name('Kawasaki Heavy Industries').id },
            { 'name': 'Pilatus PC-12', 'manufacturer_id': Manufacturer.pick.with_name('Pilatus Aircraft').id },
            { 'name': 'Pilatus PC-24', 'manufacturer_id': Manufacturer.pick.with_name('Pilatus Aircraft').id },
            { 'name': 'Leonardo AW139', 'manufacturer_id': Manufacturer.pick.with_name('Leonardo').id },
            { 'name': 'Leonardo AW189', 'manufacturer_id': Manufacturer.pick.with_name('Leonardo').id },
            { 'name': 'Piaggio P.180 Avanti', 'manufacturer_id': Manufacturer.pick.with_name('Piaggio Aerospace').id },
            { 'name': 'Piaggio P.1HH HammerHead', 'manufacturer_id': Manufacturer.pick.with_name('Piaggio Aerospace').id },
            { 'name': 'Aerospatiale Concorde', 'manufacturer_id': Manufacturer.pick.with_name('Aerospatiale').id },
            { 'name': 'Aerospatiale ATR 72', 'manufacturer_id': Manufacturer.pick.with_name('Aerospatiale').id },
            { 'name': 'Northrop Grumman B-2 Spirit', 'manufacturer_id': Manufacturer.pick.with_name('Northrop Grumman').id },
            { 'name': 'Northrop Grumman E-2 Hawkeye', 'manufacturer_id': Manufacturer.pick.with_name('Northrop Grumman').id },
            { 'name': 'Thales Watchkeeper WK450', 'manufacturer_id': Manufacturer.pick.with_name('Thales').id },
            { 'name': 'Thales Fulmar', 'manufacturer_id': Manufacturer.pick.with_name('Thales').id },
            { 'name': 'Mitsubishi MRJ', 'manufacturer_id': Manufacturer.pick.with_name('Mitsubishi Heavy Industries').id },
            { 'name': 'Mitsubishi F-2', 'manufacturer_id': Manufacturer.pick.with_name('Mitsubishi Heavy Industries').id },
            { 'name': 'Cirrus SR22', 'manufacturer_id': Manufacturer.pick.with_name('Cirrus Aircraft').id },
            { 'name': 'Cirrus SF50 Vision', 'manufacturer_id': Manufacturer.pick.with_name('Cirrus Aircraft').id },
            { 'name': 'Air Tractor AT-802', 'manufacturer_id': Manufacturer.pick.with_name('Air Tractor').id },
            { 'name': 'Air Tractor AT-502', 'manufacturer_id': Manufacturer.pick.with_name('Air Tractor').id },
            { 'name': 'Hawker Beechcraft King Air 350', 'manufacturer_id': Manufacturer.pick.with_name('Hawker Beechcraft').id },
            { 'name': 'Hawker Beechcraft Premier 1A', 'manufacturer_id': Manufacturer.pick.with_name('Hawker Beechcraft').id },
            { 'name': 'Textron Aviation Cessna 172', 'manufacturer_id': Manufacturer.pick.with_name('Textron Aviation').id },
            { 'name': 'Textron Aviation Beechcraft Baron', 'manufacturer_id': Manufacturer.pick.with_name('Textron Aviation').id },
            { 'name': 'Tupolev Tu-154', 'manufacturer_id': Manufacturer.pick.with_name('Tupolev').id },
            { 'name': 'Tupolev Tu-95', 'manufacturer_id': Manufacturer.pick.with_name('Tupolev').id },
            { 'name': 'Sikorsky UH-60 Black Hawk', 'manufacturer_id': Manufacturer.pick.with_name('Sikorsky Aircraft').id },
            { 'name': 'Sikorsky S-92', 'manufacturer_id': Manufacturer.pick.with_name('Sikorsky Aircraft').id },
            { 'name': 'Ilyushin Il-76', 'manufacturer_id': Manufacturer.pick.with_name('Ilyushin').id },
            { 'name': 'Ilyushin Il-96', 'manufacturer_id': Manufacturer.pick.with_name('Ilyushin').id },
            { 'name': 'Kaman K-MAX', 'manufacturer_id': Manufacturer.pick.with_name('Kaman Aerospace').id },
            { 'name': 'Kaman SH-2G Super Seasprite', 'manufacturer_id': Manufacturer.pick.with_name('Kaman Aerospace').id },
            { 'name': 'Beechcraft Baron', 'manufacturer_id': Manufacturer.pick.with_name('Raytheon Aircraft Company').id },
            { 'name': 'Beechcraft Bonanza', 'manufacturer_id': Manufacturer.pick.with_name('Raytheon Aircraft Company').id },
            { 'name': 'A-10 Thunderbolt II', 'manufacturer_id': Manufacturer.pick.with_name('Fairchild Republic').id },
            { 'name': 'A-10C Thunderbolt II', 'manufacturer_id': Manufacturer.pick.with_name('Fairchild Republic').id },
            { 'name': 'Dhruv', 'manufacturer_id': Manufacturer.pick.with_name('Hindustan Aeronautics Limited').id },
            { 'name': 'Chetak', 'manufacturer_id': Manufacturer.pick.with_name('Hindustan Aeronautics Limited').id },
            { 'name': 'AW139', 'manufacturer_id': Manufacturer.pick.with_name('AgustaWestland').id },
            { 'name': 'AW109', 'manufacturer_id': Manufacturer.pick.with_name('AgustaWestland').id },
            { 'name': 'F27 Friendship', 'manufacturer_id': Manufacturer.pick.with_name('Fokker').id },
            { 'name': 'F50', 'manufacturer_id': Manufacturer.pick.with_name('Fokker').id },
        ]
