from jethive.model import Model, unique
from jethive.models.plane_type import PlaneType


class Plane(Model):
    c_name = unique(str)
    c_plane_type = PlaneType
    
    @classmethod
    def seed(cls):
        return [
            {'name': 'Victory', 'plane_type_id': PlaneType.pick.with_name('A320').id},
            {'name': 'Mulena', 'plane_type_id': PlaneType.pick.with_name('A320').id},
            {'name': 'Glorious', 'plane_type_id': PlaneType.pick.with_name('A330').id},
            {'name': 'Cloudy', 'plane_type_id': PlaneType.pick.with_name('A330').id},
            {'name': 'Skyhawk Blaster', 'plane_type_id': PlaneType.pick.with_name('A350').id},
            {'name': 'Starliner', 'plane_type_id': PlaneType.pick.with_name('A350').id},
            {'name': 'Dreamliner', 'plane_type_id': PlaneType.pick.with_name('A380').id},
            {'name': 'Sunshine', 'plane_type_id': PlaneType.pick.with_name('A380').id},
            {'name': 'Breezefly', 'plane_type_id': PlaneType.pick.with_name('A220').id},
            {'name': 'Airsprint', 'plane_type_id': PlaneType.pick.with_name('A220').id},
            {'name': 'Thunderbird', 'plane_type_id': PlaneType.pick.with_name('A340').id},
            {'name': 'Silversky', 'plane_type_id': PlaneType.pick.with_name('A340').id},
            {'name': 'Stellar', 'plane_type_id': PlaneType.pick.with_name('A310').id},
            {'name': 'Lunarglide', 'plane_type_id': PlaneType.pick.with_name('A310').id},
            {'name': 'Swiftwind', 'plane_type_id': PlaneType.pick.with_name('A321').id},
            {'name': 'Firebird', 'plane_type_id': PlaneType.pick.with_name('A321').id},
            {'name': 'Eaglewing', 'plane_type_id': PlaneType.pick.with_name('A319').id},
            {'name': 'Silverstream', 'plane_type_id': PlaneType.pick.with_name('A319').id},
            {'name': 'Starship', 'plane_type_id': PlaneType.pick.with_name('A330neo').id},
            {'name': 'Bluebird', 'plane_type_id': PlaneType.pick.with_name('A330neo').id},
            {'name': 'Panther', 'plane_type_id': PlaneType.pick.with_name('737').id},
            {'name': 'Phoenix', 'plane_type_id': PlaneType.pick.with_name('737').id},
            {'name': 'Skywatcher', 'plane_type_id': PlaneType.pick.with_name('747').id},
            {'name': 'Aerowaver', 'plane_type_id': PlaneType.pick.with_name('747').id},
            {'name': 'Stardust', 'plane_type_id': PlaneType.pick.with_name('777').id},
            {'name': 'Eclipse', 'plane_type_id': PlaneType.pick.with_name('777').id},
            {'name': 'Zenith', 'plane_type_id': PlaneType.pick.with_name('787').id},
            {'name': 'Horizon', 'plane_type_id': PlaneType.pick.with_name('787').id},
            {'name': 'Skylark', 'plane_type_id': PlaneType.pick.with_name('727').id},
            {'name': 'Firefly', 'plane_type_id': PlaneType.pick.with_name('727').id},
            {'name': 'Bluestar', 'plane_type_id': PlaneType.pick.with_name('757').id},
            {'name': 'Cyan Nimbus', 'plane_type_id': PlaneType.pick.with_name('757').id},
            {'name': 'Skyward', 'plane_type_id': PlaneType.pick.with_name('767').id},
            {'name': 'Nighthawk', 'plane_type_id': PlaneType.pick.with_name('767').id},
            {'name': 'Starfly', 'plane_type_id': PlaneType.pick.with_name('737 MAX').id},
            {'name': 'Silverwing', 'plane_type_id': PlaneType.pick.with_name('737 MAX').id},
            {'name': 'Horizonstar', 'plane_type_id': PlaneType.pick.with_name('707').id},
            {'name': 'Thundercloud', 'plane_type_id': PlaneType.pick.with_name('707').id},
            {'name': 'Breezejet', 'plane_type_id': PlaneType.pick.with_name('787-10').id},
            {'name': 'Luminair', 'plane_type_id': PlaneType.pick.with_name('787-10').id},
            {'name': 'Skyjogger', 'plane_type_id': PlaneType.pick.with_name('CRJ').id},
            {'name': 'Aerojet', 'plane_type_id': PlaneType.pick.with_name('CRJ').id},
            {'name': 'Thunderchief', 'plane_type_id': PlaneType.pick.with_name('Q400').id},
            {'name': 'Silverarrow', 'plane_type_id': PlaneType.pick.with_name('Q400').id},
            {'name': 'Starshuttle', 'plane_type_id': PlaneType.pick.with_name('Global 7500').id},
            {'name': 'Aeroluxe', 'plane_type_id': PlaneType.pick.with_name('Global 7500').id},
            {'name': 'Cheetah', 'plane_type_id': PlaneType.pick.with_name('Challenger 300').id},
            {'name': 'Skyrunner', 'plane_type_id': PlaneType.pick.with_name('Challenger 300').id},
            {'name': 'Jetsetter', 'plane_type_id': PlaneType.pick.with_name('Learjet 75').id},
            {'name': 'Solaris', 'plane_type_id': PlaneType.pick.with_name('Learjet 75').id},
            {'name': 'Airspeed', 'plane_type_id': PlaneType.pick.with_name('Embraer E-Jet').id},
            {'name': 'Aerolite', 'plane_type_id': PlaneType.pick.with_name('Embraer E-Jet').id},
            {'name': 'Aviator', 'plane_type_id': PlaneType.pick.with_name('Embraer Legacy 650').id},
            {'name': 'Nightstar', 'plane_type_id': PlaneType.pick.with_name('Embraer Legacy 650').id},
            {'name': 'Voyager', 'plane_type_id': PlaneType.pick.with_name('Gulfstream G550').id},
            {'name': 'Stratosphere', 'plane_type_id': PlaneType.pick.with_name('Gulfstream G550').id},
            {'name': 'Citation II', 'plane_type_id': PlaneType.pick.with_name('Cessna Citation').id},
            {'name': 'Silver Angel', 'plane_type_id': PlaneType.pick.with_name('Cessna Citation').id},
            {'name': 'Caravan Express', 'plane_type_id': PlaneType.pick.with_name('Cessna Caravan').id},
            {'name': 'Aerohawk', 'plane_type_id': PlaneType.pick.with_name('Cessna Caravan').id},
            {'name': 'Falcon Swift', 'plane_type_id': PlaneType.pick.with_name('Dassault Falcon').id},
            {'name': 'Nimbus', 'plane_type_id': PlaneType.pick.with_name('Dassault Falcon').id},
            {'name': 'Saab Airmaster', 'plane_type_id': PlaneType.pick.with_name('Saab 340').id},
            {'name': 'Cirrus Starline', 'plane_type_id': PlaneType.pick.with_name('Saab 340').id},
            {'name': 'Supreme', 'plane_type_id': PlaneType.pick.with_name('Saab 2000').id},
            {'name': 'Safir', 'plane_type_id': PlaneType.pick.with_name('Saab 2000').id},
            {'name': 'Sukhoi Skyline', 'plane_type_id': PlaneType.pick.with_name('Sukhoi Superjet').id},
            {'name': 'Silverbird', 'plane_type_id': PlaneType.pick.with_name('Sukhoi Superjet').id},
            {'name': 'Piper Dreamstar', 'plane_type_id': PlaneType.pick.with_name('Piper PA-28').id},
            {'name': 'AeroStar', 'plane_type_id': PlaneType.pick.with_name('Piper PA-28').id},
            {'name': 'Diamond Airstream', 'plane_type_id': PlaneType.pick.with_name('Diamond DA40').id},
            {'name': 'AeroDawn', 'plane_type_id': PlaneType.pick.with_name('Diamond DA40').id},
            {'name': 'King Airfly', 'plane_type_id': PlaneType.pick.with_name('Beechcraft King Air').id},
            {'name': 'Starcraft', 'plane_type_id': PlaneType.pick.with_name('Beechcraft King Air').id},
            {'name': 'Bonanza Starlite', 'plane_type_id': PlaneType.pick.with_name('Beechcraft Bonanza').id},
            {'name': 'Silvercloud', 'plane_type_id': PlaneType.pick.with_name('Beechcraft Bonanza').id},
            {'name': 'Antonov Skyship', 'plane_type_id': PlaneType.pick.with_name('Antonov An-124').id},
            {'name': 'AeroTitanium', 'plane_type_id': PlaneType.pick.with_name('Antonov An-124').id},
            {'name': 'Kawasaki Skysurfer', 'plane_type_id': PlaneType.pick.with_name('Kawasaki P-1').id},
            {'name': 'Starjet', 'plane_type_id': PlaneType.pick.with_name('Kawasaki P-1').id},
            {'name': 'Pilatus Starwind', 'plane_type_id': PlaneType.pick.with_name('Pilatus PC-12').id},
            {'name': 'AeroGlide', 'plane_type_id': PlaneType.pick.with_name('Pilatus PC-12').id},
            {'name': 'Leonardo Aerohawk', 'plane_type_id': PlaneType.pick.with_name('Leonardo AW139').id},
            {'name': 'Skyliner', 'plane_type_id': PlaneType.pick.with_name('Leonardo AW139').id},
            {'name': 'Piaggio Aviator', 'plane_type_id': PlaneType.pick.with_name('Piaggio P.180 Avanti').id},
            {'name': 'Silverglide', 'plane_type_id': PlaneType.pick.with_name('Piaggio P.180 Avanti').id},
            {'name': 'Aerospatiale Dreamjet', 'plane_type_id': PlaneType.pick.with_name('Aerospatiale Concorde').id},
            {'name': 'AeroSonic', 'plane_type_id': PlaneType.pick.with_name('Aerospatiale Concorde').id},
            {'name': 'Spiritbird', 'plane_type_id': PlaneType.pick.with_name('Northrop Grumman B-2 Spirit').id},
            {'name': 'Skyhawk', 'plane_type_id': PlaneType.pick.with_name('Northrop Grumman B-2 Spirit').id},
            {'name': 'Hawkeye Starwatcher', 'plane_type_id': PlaneType.pick.with_name('Northrop Grumman E-2 Hawkeye').id},
            {'name': 'AeroWave', 'plane_type_id': PlaneType.pick.with_name('Northrop Grumman E-2 Hawkeye').id},
            {'name': 'Fulmar Express', 'plane_type_id': PlaneType.pick.with_name('Thales Fulmar').id},
            {'name': 'Starship Ev', 'plane_type_id': PlaneType.pick.with_name('Thales Fulmar').id},
            {'name': 'Mirage Express', 'plane_type_id': PlaneType.pick.with_name('Mitsubishi MRJ').id},
            {'name': 'Aerowind', 'plane_type_id': PlaneType.pick.with_name('Mitsubishi MRJ').id},
            {'name': 'Falcon Dreamer', 'plane_type_id': PlaneType.pick.with_name('Cirrus SR22').id},
            {'name': 'Starbird', 'plane_type_id': PlaneType.pick.with_name('Cirrus SR22').id},
            {'name': 'Visionstar', 'plane_type_id': PlaneType.pick.with_name('Cirrus SF50 Vision').id},
            {'name': 'Silverdream', 'plane_type_id': PlaneType.pick.with_name('Cirrus SF50 Vision').id},
            {'name': 'AT-802 Aviator', 'plane_type_id': PlaneType.pick.with_name('Air Tractor AT-802').id},
            {'name': 'Skyfarmer', 'plane_type_id': PlaneType.pick.with_name('Air Tractor AT-502').id},
            {'name': 'Aeromaster', 'plane_type_id': PlaneType.pick.with_name('Air Tractor AT-502').id},
            {'name': 'King Air Voyager', 'plane_type_id': PlaneType.pick.with_name('Hawker Beechcraft King Air 350').id},
            {'name': 'Starship Premier', 'plane_type_id': PlaneType.pick.with_name('Hawker Beechcraft King Air 350').id},
            {'name': 'Cessna Skyline', 'plane_type_id': PlaneType.pick.with_name('Textron Aviation Cessna 172').id},
            {'name': 'Silverstar', 'plane_type_id': PlaneType.pick.with_name('Textron Aviation Cessna 172').id},
            {'name': 'Baron Express', 'plane_type_id': PlaneType.pick.with_name('Textron Aviation Beechcraft Baron').id},
            {'name': 'AeroBaron', 'plane_type_id': PlaneType.pick.with_name('Textron Aviation Beechcraft Baron').id},
            {'name': 'Tupolev Starliner', 'plane_type_id': PlaneType.pick.with_name('Tupolev Tu-154').id},
            {'name': 'AeroWave Skyline', 'plane_type_id': PlaneType.pick.with_name('Tupolev Tu-154').id},
            {'name': 'Tu-95 Skyshaker', 'plane_type_id': PlaneType.pick.with_name('Tupolev Tu-95').id},
            {'name': 'Silverhawk', 'plane_type_id': PlaneType.pick.with_name('Tupolev Tu-95').id},
            {'name': 'Black Hawk Voyager', 'plane_type_id': PlaneType.pick.with_name('Sikorsky UH-60 Black Hawk').id},
            {'name': 'Nightbird', 'plane_type_id': PlaneType.pick.with_name('Sikorsky UH-60 Black Hawk').id},
            {'name': 'S-92 Starlifter', 'plane_type_id': PlaneType.pick.with_name('Sikorsky S-92').id},
            {'name': 'Skyking', 'plane_type_id': PlaneType.pick.with_name('Sikorsky S-92').id},
            {'name': 'Il-76 Voyager', 'plane_type_id': PlaneType.pick.with_name('Ilyushin Il-76').id},
            {'name': 'AeroTitan', 'plane_type_id': PlaneType.pick.with_name('Ilyushin Il-76').id},
            {'name': 'Il-96 Skyshaker', 'plane_type_id': PlaneType.pick.with_name('Ilyushin Il-96').id},
            {'name': 'Goldencloud', 'plane_type_id': PlaneType.pick.with_name('Ilyushin Il-96').id},
            {'name': 'K-MAX Voyager', 'plane_type_id': PlaneType.pick.with_name('Kaman K-MAX').id},
            {'name': 'AeroLifter', 'plane_type_id': PlaneType.pick.with_name('Kaman K-MAX').id},
            {'name': 'SH-2G Skyshaker', 'plane_type_id': PlaneType.pick.with_name('Kaman SH-2G Super Seasprite').id},
            {'name': 'Copperhawk', 'plane_type_id': PlaneType.pick.with_name('Kaman SH-2G Super Seasprite').id},
            {'name': 'Baron Voyager', 'plane_type_id': PlaneType.pick.with_name('Beechcraft Baron').id},
            {'name': 'SkyBaron', 'plane_type_id': PlaneType.pick.with_name('Beechcraft Baron').id},
            {'name': 'Bonanza Voyager', 'plane_type_id': PlaneType.pick.with_name('Beechcraft Bonanza').id},
            {'name': 'AeroBonanza', 'plane_type_id': PlaneType.pick.with_name('Beechcraft Bonanza').id},
            {'name': 'Thunderbolt Voyager', 'plane_type_id': PlaneType.pick.with_name('A-10 Thunderbolt II').id},
            {'name': 'Silverthunder', 'plane_type_id': PlaneType.pick.with_name('A-10 Thunderbolt II').id},
            {'name': 'A-10C Skyshaker', 'plane_type_id': PlaneType.pick.with_name('A-10C Thunderbolt II').id},
            {'name': 'AeroBolt', 'plane_type_id': PlaneType.pick.with_name('A-10C Thunderbolt II').id},
            {'name': 'Dhruv Voyager', 'plane_type_id': PlaneType.pick.with_name('Dhruv').id},
            {'name': 'SkyDhruv', 'plane_type_id': PlaneType.pick.with_name('Dhruv').id},
            {'name': 'Chetak Skyflyer', 'plane_type_id': PlaneType.pick.with_name('Chetak').id},
            {'name': 'AeroChetak', 'plane_type_id': PlaneType.pick.with_name('Chetak').id},
            {'name': 'AW139 Voyager', 'plane_type_id': PlaneType.pick.with_name('AW139').id},
            {'name': 'Silverwave', 'plane_type_id': PlaneType.pick.with_name('AW139').id},
            {'name': 'AW109 Skyliner', 'plane_type_id': PlaneType.pick.with_name('AW109').id},
            {'name': 'Aero109', 'plane_type_id': PlaneType.pick.with_name('AW109').id},
            {'name': 'F27 Skyshuttle', 'plane_type_id': PlaneType.pick.with_name('F27 Friendship').id},
            {'name': 'Silverfriend', 'plane_type_id': PlaneType.pick.with_name('F27 Friendship').id},
            {'name': 'F50 Skybird', 'plane_type_id': PlaneType.pick.with_name('F50').id},
            {'name': 'AeroF50', 'plane_type_id': PlaneType.pick.with_name('F50').id},
        ]